[build]
  command = "cd app && pnpm install && pnpm build"
  publish = "app/.next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/demo/*"
  to = "/.netlify/functions/next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next/:splat"
  status = 200 