[build]
  command = "cd app && pnpm install && pnpm build"
  publish = "."

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/demo/*"
  to = "/.netlify/functions/next/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/.netlify/functions/next/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next/:splat"
  status = 200
  force = true 